# Generated by Django 4.2 on 2025-03-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_sekce_partner_sekce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
