# Generated by Django 4.2 on 2025-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_sekce_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
