# Generated by Django 5.0.7 on 2025-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partner_ico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='partner',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
