# Generated by Django 4.2 on 2025-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_partner_latitude_alter_partner_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='partner',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
