# Generated by Django 4.2 on 2025-04-19 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0010_partner_sekce_sekundarni_partnersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('zpusob', models.CharField(choices=[('telefon', 'Telefon'), ('osobne', 'Osobně'), ('email', 'E-mail'), ('sms', 'SMS'), ('jinak', 'Jinak')], max_length=20)),
                ('vysledek', models.CharField(choices=[('nezajem', 'Nemá zájem'), ('schuzka', 'Domluvená schůzka'), ('zajem', 'Má zájem'), ('uzavreno', 'Obchod uzavřen'), ('free_ucet', 'Free účet')], max_length=20)),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('kontaktoval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakty', to='partners.partner')),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
    ]
