# Generated by Django 4.2 on 2025-04-19 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0011_kontakthistorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='key_account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienti', to=settings.AUTH_USER_MODEL),
        ),
    ]
