# Generated by Django 4.2 on 2025-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_alter_partner_created_by_alter_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakthistorie',
            name='vysledek',
            field=models.CharField(choices=[('nezajem', 'Nemá zájem'), ('schuzka', 'Domluvená schůzka'), ('zajem', 'Má zájem'), ('uzavreno', 'Obchod uzavřen'), ('free_ucet', 'Free účet'), ('predbezny', 'Předběžný zájem')], max_length=20),
        ),
    ]
