# Generated by Django 5.2 on 2025-09-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_alter_kontakthistorie_vysledek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakthistorie',
            name='vysledek',
            field=models.CharField(choices=[('nezajem', 'Nemá zájem'), ('schuzka', 'Domluvená schůzka'), ('zajem', 'Má zájem'), ('uzavreno', 'Obchod uzavřen'), ('free_ucet', 'Free účet'), ('predbezny', 'Předběžný zájem'), ('no_time', 'Nemá čas'), ('nevi', 'Neví')], max_length=20),
        ),
    ]
